### ISSUE TITLE
docker build ist not working (nix build error = 1 dependencies couldn't be built)

### ISSUE THREAD

**Issue by TheDevKnight** [EmurgoVN/cardano_docker#5]
Hi,

ive got the following error 

`Step 12/13 : RUN . /home/cardano/.nix-profile/etc/profile.d/nix.sh &&   nix-build -A connectScripts.mainnetWallet -o connect-to-mainnet
 ---> Running in c48cf1042870
warning: unknown setting 'binary-caches-public-keys'
building '/nix/store/yxs7w5kmy1pf3awbqvv1mspavzyv3zar-61fbdb47a69f78998f55207e64122a0798047b5d.tar.gz.drv'...
warning: unknown setting 'binary-caches-public-keys'
building '/nix/store/bds29azbsq3fva64dpv67771q4g2dc2l-61fbdb47a69f78998f55207e64122a0798047b5d.tar.gz-unpacked.drv'...
these derivations will be built:
  /nix/store/9sdv2xh9c0r9ggbxlqv4wgx2i1xmjyi1-wallet-connect-to-mainnet.drv
these paths will be fetched (23.29 MiB download, 154.37 MiB unpacked):
  /nix/store/44dbwrwfy6lj45jy02d0rjbj9930nwf3-patch-2.7.5
  /nix/store/5dnva19r2z20jahsx3jxm565qwjxsynl-bzip2-1.0.6.0.1
  /nix/store/7ydrnkyarbpd3qa3fzhg8ms6nnl70g3l-lz4-131
  /nix/store/871adhqrxl37bpi5w9g9g6y0i1n4f9cd-findutils-4.6.0
  /nix/store/8g2x5qjqyv9a7glmvpzv1wylnbf1cwvw-gnumake-4.2.1
  /nix/store/8i9xl98kswgbani8bkrxr023nh4i51k5-attr-2.4.47
  /nix/store/9j72vyzlcikn12l72nhdig7sksc0z38c-google-gflags-2.2.0
  /nix/store/9mf8jxwg2z705z5idzgbn2zzsby2va97-ekg-wai-0.1.0.2-data
  /nix/store/abk6h8g0hj6dyk75h320mgls3ygshl0w-gzip-1.8
  /nix/store/afs50wwrblgpnmva9ibzdjv7nqr7b6y3-jemalloc-4.5.0
  /nix/store/b6571mr8rfn82psy4lhizaz3w09fnz6a-acl-2.2.52
  /nix/store/bl1mv4i6ywns4hy0nvbdn93m9i12ryna-patchelf-0.9
  /nix/store/by3lqpgph3c4maz6vb2xhd64vhagfc67-bzip2-1.0.6.0.1-bin
  /nix/store/cr49q6vvyhfs48dg15ys3mghfzgc80i7-openssl-1.0.2l
  /nix/store/d4yib20lqn7krrqmm0wwbwjxjfa78xqp-coreutils-8.28
  /nix/store/dsjkns6r9g860vn0idy2072f6cli0gky-stdenv
  /nix/store/dy1fjqfnk1w0q2nix38b21cjqx218val-paxctl-0.9
  /nix/store/flb9ar1xdd13c606aa4my9miy3iv4vyk-bash-4.4-p12
  /nix/store/h5c2vfaxhpv7v0p1vlh3h7sdiphsi4rv-gnused-4.4
  /nix/store/i8wz3m067dzbs5x2glhxvcg7lvds1942-zlib-1.2.11
  /nix/store/ic5criggbnpfrdnxdhdpkq11birkfz5m-gcc-6.4.0-lib
  /nix/store/j41pm590lflva7kkx643kycix8njjrld-xz-5.2.3
  /nix/store/jn350na5wcshwsixpq1wbskdp7r3x0r3-openssl-1.0.2l-bin
  /nix/store/k1aa4d2riraz6nx3zqhsanasjpfhhhc3-cardano-sl-wallet-1.0.3
  /nix/store/kkrg56qh1l655bcdr6amyp7k59ndf81z-diffutils-3.6
  /nix/store/kpnj0h0340wd0i86q0523527ikbz62ll-gnutar-1.29
  /nix/store/lp49ww69vllq2mwsd38rpzfr9h448397-ed-1.14.2
  /nix/store/lwyhqyx7sm3va37pv1jxzaz2v7g4b4fv-snappy-1.1.4
  /nix/store/pd5c65d1d99hn33831lxmrgqhnxg7q6z-pcre-8.40
  /nix/store/pyqzyl3yvam1magahsm8xahx5hs1ngh9-gawk-4.1.4
  /nix/store/s6wz7l5h0ya6qciy0xcxwv05l50snfy8-gnugrep-3.1
  /nix/store/vqyfgdg7i3hdh3q8zp0xx3nrzgja4525-cardano-config
  /nix/store/xq5dw2qxz9b82xh53119xd40ffmwabd4-rocksdb-5.1.2
  /nix/store/yj4b630bm6yscdw8j2sa1sb61j3rdqsy-perl-5.24.2
  /nix/store/z5z8ldravlksmw7fqalyzr4i75x8ayjv-gmp-6.1.2
  /nix/store/zpg78y1mf0di6127q6r51kgx2q8cxsvv-glibc-2.25-49
  /nix/store/zv86mp9qr1kk2sxv174fxrmly82wakr0-xz-5.2.3-bin
warning: substituter 'https://hydra.iohk.io' does not have a valid signature for path '/nix/store/vqyfgdg7i3hdh3q8zp0xx3nrzgja4525-cardano-config'
warning: substituter 'https://hydra.iohk.io' does not have a valid signature for path '/nix/store/k1aa4d2riraz6nx3zqhsanasjpfhhhc3-cardano-sl-wallet-1.0.3'
cannot build derivation '/nix/store/9sdv2xh9c0r9ggbxlqv4wgx2i1xmjyi1-wallet-connect-to-mainnet.drv': 1 dependencies couldn't be built
error: build of '/nix/store/9sdv2xh9c0r9ggbxlqv4wgx2i1xmjyi1-wallet-connect-to-mainnet.drv' failed
The command '/bin/sh -c . /home/cardano/.nix-profile/etc/profile.d/nix.sh &&   nix-build -A connectScripts.mainnetWallet -o connect-to-mainnet' returned a non-zero code: 1`

What can i do?

Regards

**Comment by loganemurgo** [comment]
Thanks @TheDevKnight!
I'll apply the public key fix to the explorer container shortly.
